name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # ==========================================================
  # TERRAFORM PLAN
  # ==========================================================
  terraform-plan:
    name: Terraform Plan
    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        working-directory: env/dev
        shell: powershell

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login `
            --service-principal `
            --username "${{ vars.AZURE_CLIENT_ID }}" `
            --password "${{ vars.AZURE_CLIENT_SECRET }}" `
            --tenant "${{ vars.AZURE_TENANT_ID }}"

          az account set `
            --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"

      - name: Terraform Init
        run: |
          terraform init -input=false

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false


  # ==========================================================
  # TERRAFORM APPLY
  # ==========================================================
  terraform-apply:
    name: Terraform Apply
    runs-on: [self-hosted, Windows, X64]

    needs: terraform-plan

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: env/dev
        shell: powershell

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login `
            --service-principal `
            --username "${{ vars.AZURE_CLIENT_ID }}" `
            --password "${{ vars.AZURE_CLIENT_SECRET }}" `
            --tenant "${{ vars.AZURE_TENANT_ID }}"

          az account set `
            --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"

      - name: Terraform Init
        run: |
          terraform init -input=false

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve