name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # ==========================================================
  # TERRAFORM PLAN
  # ==========================================================
  terraform-plan:
    name: Terraform Plan
    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        working-directory: env/dev
        shell: powershell

    steps:

      # --------------------------------------------------------
      # Checkout
      # --------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Debug Workspace
        working-directory: .
        shell: powershell
        run: |
          Write-Host "=== Current Directory ==="
          Get-Location

          Write-Host "=== GitHub Workspace ==="
          Write-Host "$env:GITHUB_WORKSPACE"

          Write-Host "=== Root Contents ==="
          Get-ChildItem

          Write-Host "=== env/dev Check ==="
          if (Test-Path ".\env\dev") {
            Write-Host "SUCCESS: env/dev EXISTS"
            Get-ChildItem ".\env\dev"
          }
          else {
            Write-Host "ERROR: env/dev DOES NOT EXIST"
          }

      # --------------------------------------------------------
      # Setup Terraform
      # --------------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --------------------------------------------------------
      # Check Azure Variables
      # --------------------------------------------------------
      - name: Check Azure Variables
        shell: powershell
        run: |
          if ([string]::IsNullOrEmpty("${{ vars.AZURE_CLIENT_ID }}")) {
            Write-Host "AZURE_CLIENT_ID is EMPTY"
          }
          else {
            Write-Host "AZURE_CLIENT_ID is SET"
          }

          if ([string]::IsNullOrEmpty("${{ vars.AZURE_CLIENT_SECRET }}")) {
            Write-Host "AZURE_CLIENT_SECRET is EMPTY"
          }
          else {
            Write-Host "AZURE_CLIENT_SECRET is SET"
          }

          if ([string]::IsNullOrEmpty("${{ vars.AZURE_TENANT_ID }}")) {
            Write-Host "AZURE_TENANT_ID is EMPTY"
          }
          else {
            Write-Host "AZURE_TENANT_ID is SET"
          }

          if ([string]::IsNullOrEmpty("${{ vars.AZURE_SUBSCRIPTION_ID }}")) {
            Write-Host "AZURE_SUBSCRIPTION_ID is EMPTY"
          }
          else {
            Write-Host "AZURE_SUBSCRIPTION_ID is SET"
          }

      # --------------------------------------------------------
      # Azure Login
      # --------------------------------------------------------
      - name: Azure Login
        shell: powershell
        run: |
          az login `
            --service-principal `
            --username "${{ vars.AZURE_CLIENT_ID }}" `
            --password "${{ vars.AZURE_CLIENT_SECRET }}" `
            --tenant "${{ vars.AZURE_TENANT_ID }}"

      # --------------------------------------------------------
      # Set Azure Subscription
      # --------------------------------------------------------
      - name: Set Azure Subscription
        shell: powershell
        run: |
          az account set `
            --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"

      # --------------------------------------------------------
      # Check Azure Login
      # --------------------------------------------------------
      - name: Check Azure Login
        shell: powershell
        run: |
          az account show

      # --------------------------------------------------------
      # Terraform Format
      # --------------------------------------------------------
      - name: Terraform Format
        run: |
          terraform fmt -check -recursive

      # --------------------------------------------------------
      # Terraform Init
      # --------------------------------------------------------
      - name: Terraform Init
        run: |
          terraform init

      # --------------------------------------------------------
      # Terraform Validate
      # --------------------------------------------------------
      - name: Terraform Validate
        run: |
          terraform validate

      # --------------------------------------------------------
      # TFLint
      # --------------------------------------------------------
      - name: Check TFLint
        shell: powershell
        run: |
          tflint --version

      - name: TFLint Init
        shell: powershell
        run: |
          tflint --init

      - name: TFLint
        shell: powershell
        run: |
          tflint

      # --------------------------------------------------------
      # Install tfsec - Windows
      # --------------------------------------------------------
      - name: Install tfsec
        shell: powershell
        run: |
          $tfsecPath = "$env:RUNNER_TEMP\tfsec.exe"

          if (Test-Path $tfsecPath) {
            Write-Host "tfsec already exists."
          }
          else {
            Write-Host "Downloading tfsec..."

            Invoke-WebRequest `
              -Uri "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe" `
              -OutFile $tfsecPath
          }

          Unblock-File -Path $tfsecPath

          & $tfsecPath --version

      # --------------------------------------------------------
      # tfsec Security Scan
      # --------------------------------------------------------
      - name: tfsec Security Scan
        shell: powershell
        run: |
          & "$env:RUNNER_TEMP\tfsec.exe" .

      # --------------------------------------------------------
      # Terraform Plan
      # --------------------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan


  # ==========================================================
  # TERRAFORM APPLY
  # ==========================================================
  terraform-apply:
    name: Terraform Apply
    runs-on: [self-hosted, Windows, X64]

    needs: terraform-plan

    # Apply ONLY when code is pushed to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: env/dev
        shell: powershell

    steps:

      # --------------------------------------------------------
      # Checkout
      # --------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4

      # --------------------------------------------------------
      # Setup Terraform
      # --------------------------------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # --------------------------------------------------------
      # Azure Login
      # --------------------------------------------------------
      - name: Azure Login
        shell: powershell
        run: |
          az login `
            --service-principal `
            --username "${{ vars.AZURE_CLIENT_ID }}" `
            --password "${{ vars.AZURE_CLIENT_SECRET }}" `
            --tenant "${{ vars.AZURE_TENANT_ID }}"

      # --------------------------------------------------------
      # Set Azure Subscription
      # --------------------------------------------------------
      - name: Set Azure Subscription
        shell: powershell
        run: |
          az account set `
            --subscription "${{ vars.AZURE_SUBSCRIPTION_ID }}"

      # --------------------------------------------------------
      # Check Azure Login
      # --------------------------------------------------------
      - name: Check Azure Login
        shell: powershell
        run: |
          az account show

      # --------------------------------------------------------
      # Terraform Init
      # --------------------------------------------------------
      - name: Terraform Init
        run: |
          terraform init

      # --------------------------------------------------------
      # Terraform Validate
      # --------------------------------------------------------
      - name: Terraform Validate
        run: |
          terraform validate

      # --------------------------------------------------------
      # Terraform Plan
      # --------------------------------------------------------
      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan

      # --------------------------------------------------------
      # Terraform Apply
      # --------------------------------------------------------
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan